Random Forest is a supervised machine learning algorithm as its name tells that it creates the forest with a number of trees. 

More specifically more trees in the forest the more robust will be the forest, in same manner higher number of trees resulted in high number of accuracy results.

In decision tree algorithm calculating these nodes and forming the rules will happen using the information gain and gini index calculations.

In random forest algorithm, Instead of using information gain or gini index for calculating the root node, the process of finding the root node and splitting the feature nodes will happen randomly. Will look about in detail in the coming section.

## Advantages of random forest algorithm

Below are the advantages of random forest algorithm compared with other classification algorithms.

1.The overfitting problem will never come when we use the random forest algorithm in any classification problem.

2.The same random forest algorithm can be used for both classification and regression task.

3.The random forest algorithm can be used for feature engineering.

Which means identifying the most important features out of the available features from the training dataset.

In [28]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [4]:
iris = load_iris()

In [7]:
data = pd.DataFrame(iris.data, columns=iris.feature_names)

In [9]:
data['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

In [10]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [11]:
# Create a new column that for each row, generates a random number between 0 and 1, and
# if that value is less than or equal to .75, then sets the value of that cell as True
# and false otherwise. This is a quick and dirty way of randomly assigning some rows to
# be used as the training data and some as the test data.
data['is_train'] = np.random.uniform(0, 1, len(data)) <= .75

In [13]:
train, test = data[data['is_train'] == True], data[data['is_train'] == False]

In [14]:
train.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
2                4.7               3.2                1.3               0.2   
5                5.4               3.9                1.7               0.4   
6                4.6               3.4                1.4               0.3   
7                5.0               3.4                1.5               0.2   

  species  is_train  
0  setosa      True  
2  setosa      True  
5  setosa      True  
6  setosa      True  
7  setosa      True

In [15]:
# Show the number of observations for the test and training dataframes
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:',len(test))

Number of observations in the training data: 113
Number of observations in the test data: 37


In [16]:
# Create a list of the feature column's names
features = data.columns[:4]

In [18]:
# train['species'] contains the actual species names. Before we can use it,
# we need to convert each species name into a digit. So, in this case there
# are three species, which have been coded as 0, 1, or 2.
y = pd.factorize(train['species'])[0]

In [20]:
clf = RandomForestClassifier(n_jobs=2, random_state=0)

In [21]:
clf.fit(train[features], y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [22]:
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2], dtype=int64)

In [23]:
clf.predict_proba(test[features])[0:10]

array([[1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.98, 0.02, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ]])

In [27]:
# Create actual english names for the plants for each predicted plant class
preds = iris.target_names[clf.predict(test[features])]

preds

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'versicolor', 'virginica', 'virginica', 'virginica',
       'virginica'], dtype='<U10')

In [26]:
# Create confusion matrix
pd.crosstab(test['species'], preds, rownames=['Actual Species'], colnames=['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 15           0          0
versicolor              0           9          0
virginica               0           1         12

In [29]:
print(classification_report(test['species'], preds))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       0.90      1.00      0.95         9
   virginica       1.00      0.92      0.96        13

    accuracy                           0.97        37
   macro avg       0.97      0.97      0.97        37
weighted avg       0.98      0.97      0.97        37



In [30]:
print(confusion_matrix(test['species'], preds))

[[15  0  0]
 [ 0  9  0]
 [ 0  1 12]]
